openapi: '3.0.0'
servers:
  - url: https://example-magento-store.com/rest
info:
  version: '2.4'
  title: Amazon Pay Magento Module API
  description: >-
    API reference for the endpoints exposed by the Amazon Pay for Magento 2
    module to manage Amazon Checkout Sessions.
tags:
  - name: amazonPayCheckoutSessionManagement
    description: Manage Amazon Checkout Sessions
paths:
  '/V1/amazon-checkout-session/config/{cart-id}':
    get:
      tags:
        - amazonPayCheckoutSessionManagement
      description: Fetches configuration values used to generate an Amazon Pay button
      operationId: amazonPayCheckoutSessionManagementGetConfigGet
      parameters:
        - $ref: '#/components/parameters/uniqueCartId'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: an array of config values
              examples:
                configResponse:
                  $ref: '#/components/examples/configResponse'
  '/V1/amazon-checkout-session/{checkout-session-id}/payment-descriptor':
    get:
      tags:
        - amazonPayCheckoutSessionManagement
      description: Returns a string to display next to the amazon payment method at checkout
      operationId: amazonPayCheckoutSessionManagementGetPaymentDescriptorGet
      parameters:
        - $ref: '#/components/parameters/checkoutSessionIdParam'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              schema:
                type: string
              example:
                "Your selected Amazon payment method"
  '/V1/amazon-checkout-session/{checkout-session-id}/billing-address':
    get:
      tags:
        - amazonPayCheckoutSessionManagement
      description: >-
        Fetches the billing address associated with a session for an active cart
        ID
      operationId: amazonPayCheckoutSessionManagementGetBillingAddressGet
      parameters:
        - $ref: '#/components/parameters/checkoutSessionIdParam'
      responses:
        '200':
          description: 200 Success.
          content:
            application/json:
              schema:
                type: string
                description: false if no billing address defined in current session
              example:
                false
  '/V1/amazon-checkout-session/{checkout-session-id}/shipping-address':
    get:
      tags:
        - amazonPayCheckoutSessionManagement
      description: >-
        Fetches the shipping address associated with a session for an active
        cart ID
      operationId: amazonPayCheckoutSessionManagementGetShippingAddressGet
      parameters:
        - $ref: '#/components/parameters/checkoutSessionIdParam'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              schema:
                type: string
                description: array of shipping addresses associated with the current session
              examples:
                shippingResponse:
                  $ref: '#/components/examples/shippingResponse'
  '/V1/amazon-checkout-session/{checkout-session-id}/update/{cart-id}':
    post:
      tags:
        - amazonPayCheckoutSessionManagement
      description: >-
        Updates an Amazon checkout session with shipping and payment information
        set in a Magento checkout flow
      operationId: amazonPayCheckoutSessionManagementUpdateCheckoutSessionPost
      parameters:
        - $ref: '#/components/parameters/checkoutSessionIdParam'
        - $ref: '#/components/parameters/uniqueCartId'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              schema:
                type: string
              examples:
                withCheckoutSession:
                  $ref: '#/components/examples/updateResponseWithCheckoutSession'
                withoutCheckoutSession:
                  $ref: '#/components/examples/updateResponseWithoutCheckoutSession'
  '/V1/amazon-checkout-session/{checkout-session-id}/complete/{cart-id}':
    post:
      tags:
        - amazonPayCheckoutSessionManagement
      description: >-
        Completes the checkout session and returns a success indicator and a
        Magento order ID
      operationId: amazonPayCheckoutSessionManagementCompleteCheckoutSessionPost
      parameters:
        - $ref: '#/components/parameters/checkoutSessionIdParam'
        - $ref: '#/components/parameters/uniqueCartId'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              examples:
                completeSuccess:
                  $ref: '#/components/examples/completeResponseSuccess'
  '/V1/amazon-checkout-session/signin/{buyer-token}':
    get:
      tags:
        - amazonPayCheckoutSessionManagement
      description: >-
        If Sign in with Amazon is enabled, authenticates an Amazon customer with the Magento store and returns a customer bearer token that a custom frontend can use to manage the customer session.<br/><br/>
        If Sign in with Amazon is disabled, 'success' will be false and an error message will be returned.<br/><br/>
        If the Amazon email is already associated with a Magento store customer's email, 'success' will be false, and an error message will be returned along with the matching email address. The customer should be redirected to a store sign in page where they can supply the password for the existing store account.
      operationId: amazonPayCheckoutSessionManagementSignInPost
      parameters:
        - $ref: '#/components/parameters/buyerToken'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/signInResponseSchema'
                  - $ref: '#/components/schemas/signInFailSchema'
                  - $ref: '#/components/schemas/signInAlreadyExistsSchema'
              examples:
                signInSuccess:
                  $ref: '#/components/examples/signInSuccess'
                signInBadToken:
                  $ref: '#/components/examples/signInBadToken'
                signInAlreadyExists:
                  $ref: '#/components/examples/signInAlreadyExists'
                signInDisabled:
                  $ref: '#/components/examples/signInDisabled'
  '/V1/amazon-checkout-session/setcustomerlink':
    post:
      tags:
        - amazonPayCheckoutSessionManagement
      description: >-
        Links an Amazon account with an existing Magento store account by supplying the Magento account's password with the buyerToken.
      requestBody:
        description: JSON body including Amazon buyerToken and Magento password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                buyerToken:
                  type: string
                password:
                  type: string
            examples:
              setLinkBody:
                $ref: '#/components/examples/setLinkSuccess'
      responses:
        '200':
          description: 200 Success
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/signInResponseSchema'
                  - $ref: '#/components/schemas/signInFailSchema'
              examples:
                signInSuccess:
                  $ref: '#/components/examples/signInSuccess'
                signInBadPassword:
                  $ref: '#/components/examples/signInBadPassword'
                signInBadToken:
                  $ref: '#/components/examples/signInBadToken'
              
components:
  schemas:
    signInResponseSchema:
      type: object
      properties:
        success:
          type: boolean
        customer_id:
          type: integer
        customer_email:
          type: string
        customer_firstname:
          type: string
        customer_last:
          type: string
        customer_bearer_token:
            type: string
    signInFailSchema:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    signInAlreadyExistsSchema:
      type: object
      properties:
        success:
          type: boolean
        customer_email:
          type: string
        message:
          type: string
  parameters:
    checkoutSessionIdParam:
      name: checkout-session-id
      in: path
      description: Amazon checkout session ID associated with the active cutomer cart/quote
      required: true
      schema:
        type: string
    uniqueCartId:
      name: cart-id
      in: path
      description: Unique 32-character cart ID
      required: true
      schema:
        type: string
    buyerToken:
      name: buyer-token
      in: path
      description: Token returned from Amazon-hosted authentication service
      required: true
      schema:
        type: string
  examples:
    configResponse:
      summary: 'Array of cart config values'
      value:
        - AY7CV2FF6QJU1
        - USD
        - Gold
        - en_US
        - true
        - true
        - >-
          {"signInReturnUrl":"https://app.m242.test/amazon_pay/login/authorize/","signInCancelUrl":"https://app.m242.test/","storeId":"amzn1.application-oa2-client.6f774de2482149b18e5df3796d0aef0f","signInScopes":["name","email"]}
        - >-
          jbAeuENvsxhtonat+82IHmEYYGBtiVxaufSdTdF+8h0OaP+efVqTDaBCC42ubIIw/vEgrLjgHtZ8xspKsasycWYAe+Pr/W9Ja3/q2B3YsScZZ74QTMPad5IVguUI2F24LxK5WCw0B1yRsLphdRvqntWMoJLDdn+qYsl6wheN7+S7i+eKeR0jqkOoSVvFHpFYgktHO0aRMBSyvi/G6CfaMbJBfDb94dRPrS/IRNJ+zP0v5UySQ5T5WQn8j/R55KWhh+LntNInbqdyXaGjatNGkkfW7QZWSb0E6Rh5svDg267UtsEpN+6NXjJ0WwxVT56Avkn+5VOVRN73oFkVOnMLWQ==
        - >-
          {"webCheckoutDetails":{"checkoutReviewReturnUrl":"https://app.m242.test/amazon_pay/login/checkout/","checkoutCancelUrl":"https://app.m242.test/"},"storeId":"amzn1.application-oa2-client.6f774de2482149b18e5df3796d0aef0f"}
        - >-
          LWzCGzOyZYBB6qP/NgeOyGi9ZT209md2wc/9QEqHrgsBasUB7FnpbNC4MQ0vgeU2acMaUM4kAXAd0Z7gpJXOPbqpLWkIx5gh25cahTVc0BusImZkC80Zc4VSuf4xY4gL/Yt4zDZ9mkbs0cO7tG/B4hNMhn0k5Myb4u7cQAS7HuJ0Q4uar+RWEeeYGObrN1TjBWI24N/aMZcXh5B0hIcx1o035TOlET8Aj0R/dwOBdLm3rAVnmwQVAiRygN9GyG7RtVelzjlOaWfMbWMURfaEciV8qVKDBIxRO7INw1+vaap+wg6Bw0G1ZRaDAsDSx13RuHupOiXQNB4+eHRJd+z8WQ==
        - >-
          {"webCheckoutDetails":{"checkoutMode":"ProcessOrder","checkoutResultReturnUrl":"https://app.m242.test/amazon_pay/checkout/completeSession/","checkoutCancelUrl":"https://app.m242.test/"},"storeId":"amzn1.application-oa2-client.6f774de2482149b18e5df3796d0aef0f","paymentDetails":{"paymentIntent":"Authorize","canHandlePendingAuthorization":false,"chargeAmount":{"amount":0,"currencyCode":null},"presentmentCurrency":null},"merchantMetadata":{"merchantReferenceId":null,"merchantStoreName":null,"customInformation":"Magento Version: 2.4.2, Plugin Version: 5.6.0"}}
        - >-
          EwBIDcl3DCBb8Vw8VCduhmFX0VK0ATG87OZfZm2S2evue2cOMYS8DxLwlV9F1HgsRTACpyS9bOMFP+BQtZptJ6gaH5MwtEeZHeh4ntBM23HShw0ILDh5NQGgmotknAcWg3N4zUgYPhXbK3KQ0Aln9qby1nPgGjyvnD8r9ymzwUVbEsz54esivb/TBpNfNx8f7qFNqV1qU71u8oodzacIn8twep+4SJ/KReyo4SnuFRGwj2+iE8p0orMkBDLMsCa6etuiOSGpiKuw3btoffXasXRZOhhr7Yy3f0KdRWlE34UxHaYZz379mvFRBSnedO+SMeGzgaPpx8C8VY1CUyK2lg==
        - AGMJ4CRQPX634UDIURL2FUZT
    shippingResponse:
      summary: 'Shipping address associated with Amazon account'
      value:
        - city: Chicago
          firstname: Susie
          lastname: Smith
          country_id: US
          street:
          - 10 Ditka Ave
          - Suite 2500
          postcode: '60602'
          company: ''
          telephone: 800-000-0000
          region: Illinois
          region_id: '23'
          region_code: IL
          email: spencer+alpha@beargroup.com
    updateResponseWithCheckoutSession:
      summary: 'Active Amazon checkout session'
      value:
        "https://apay-us.amazon.com/checkout/processing?amazonCheckoutSessionId=3e414d40-960f-486c-8b55-2ace5df08202"
    updateResponseWithoutCheckoutSession:
      summary: 'No active checkout session'
      value:
        []
    completeResponseSuccess:
      summary: 'Successful checkout session completion'
      value:
        - true
        - "99"
    signInSuccess:
      summary: 'Successful store sign-in from Amazon buyer token'
      value:
        - 
          success: true
          customer_id: 201
          customer_firstname: "Susie"
          customer_last: "Smith"
          customer_bearer_token: "0wjzxdjnaus5dxdy9qwz2kgp9poftu1u"
    setLinkSuccess:
      summary: 'Valid post body for /setcustomerlink'
      value:
        buyerToken: eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoiZm1rajlPZTAzUm1yRG1KWHNzbzhNQSIsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiS2Q4Si1wdXBFTEFGXzhaeCJ9.TOUshEhmRJfimBJI73IUke1zYeajFd-agj3ZXpJI-vE.VhT9gQSZ5KOOL7G1.9aVEnZ-VbfKfjJbQykzbFYeADRq7ZeBbRrrigGRhefTUB-RFZ32Aao37qhXoY2RN8JhMvxtr-r9iAQvrQmFLv9x2atXrDBRMB-jJWVWTZDvrmg6SmckbydHBhynL-GyEYuXAXrWnQV4SSY076D8wSVwXO1t5XISnJndqNTLB9rAvYF6fF3Y4HDZ9kPMZYIj7s2lI6kuI9xipEY5hB0WQqj7SlJrz4vjSk_qekt6oRPW1l_w22vGN_3CBKtk-ECeVxg.HCGVKINr557b2hxk77webg
        password: Password
    signInBadPassword:
      summary: 'Error response for wrong password supplied'
      value:
        -
          success: false
          message: The password supplied was incorrect
    signInBadToken:
      summary: 'Error response for invalid buyerToken'
      value:
        -
          success: false
          message: Amazon buyerId is empty
    signInAlreadyExists:
      summary: 'Error response for existing Magento store customer'
      value:
        -
          success: false
          customer_email: customer@amazon.com
          message: A store account for this email address already exists. Please enter your store account password to log in without leaving the store.
    signInDisabled:
      summary: 'Error message for Sign in with Amazon Disabled'
      value:
        -
          success: false
          message: Amazon Sign-in is disabled
  
